services:
  redis: 
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data      
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    restart: unless-stopped

  math-bot:
    build: .
    container_name: math-bot-container
    env_file: .env
    depends_on:
      - redis
    environment:
      - REDIS=redis:6379      
    restart: unless-stopped

volumes:
  redis-data:
#   pgdata: